- hosts: all

  vars:
    newuser: Tux
  become: true #do as sudo
  tasks:
    - name: start gracefully #i do this to make sure that at least one task is capable of running
      debug:
        msg: "playbook begins"

    - name: check if user already exists
      command: id -u {{ newuser }}
      register: user_exists
      ignore_errors: true

    - name: create user named Tux
      ansible.builtin.user:
        name: "{{ newuser }}"
      when: user_exists is failed

    - name: new user created 
      debug:
        msg: the user named {{ newuser }} has been created
      when: user_exists is failed

    - name: show a message if user already exists
      debug:
        msg: the user already exists
      when: user_exists is succeeded    


#n00b friendly guide
#run this playbook with
#ansible-playbook -i inventory newuser-playbook.yaml
#assuming you