 ###Given the new user and a .pub or public key file, you will
###Create the user
### write the contents to /home/user/.ssh/authorized_keys for the newuser

- hosts: all

  vars:
    newuser: replace
    publickey: replace
  become: true
  tasks:
#    - name: check if user already exists
#      command: id -u {{ newuser }}
#      register: user_exists
#      ignore_errors: true
#
#    - name: create user named {{ newuser }}
#      ansible.builtin.user:
#        name: "{{ newuser }}"
#      when: user_exists is failed
#
#    - name: new user created 
#      debug:
#        msg: the user named {{ newuser }} has been created
#      when: user_exists is failed
#
#    - name: show a message if user already exists
#      debug:
#        msg: the user already exists
#      when: user_exists is succeeded

    - name: store publickey in newuser.
      ansible.builtin.lineinfile:
        path: /home/{{ newuser }}/.ssh/authorized_keys
        line: "\n #Created by Ansible Playbook \n{{ publickey }}\n"
        create: true